version: 3

tasks:
  default:
    cmds:
      - deno fmt .
      # - deno lint .
      - gofmt -w .
      - golangci-lint run ./... --fix
  test:
    cmds:
      - go test -race ./... -count=1
      # commenting out so we don't rely on public website
      # test does not run because of issue with localhost and chromedp
      # - go run examples/basic/scrape_webpage/main.go
