version: 3

tasks:
  default:
    cmds:
      - deno fmt .
      # - deno lint .
      - gofmt -w .
      - golangci-lint run ./... --fix
  test:
    cmds:
      - go test -race ./...
      - go run examples/basic/scrape_webpage/main.go
